version: "3.9"

services:
    php:
        container_name: tatrapak-web
        image: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "8102:80"